### PR TITLE
remove User trait

### PR DESCRIPTION
**Pull request by mkolopanis**
removes the currently implemented User and traits. Leaves these application specific which attach to the Daemon with channels.

This basically requires running the Daemon from the application User process, but that should be fine I think.

In an attempt to remove duplicated code, I have the SendTransaction use the same kind of channel to send user primitives to the daemon. It makes an extra sender whose receiver is immediately dropped.
Maybe there is a better way that doesn't coping the same match block around twice.

@xpromache is this what you hand in mind about removing the current User trait and implementation?
Still having the trouble that it needs the one off because of the multiplexed users in the testing.

### CODE REVIEW

**Comment by mkolopanis** [comment]
hmm except windows does not appear to be happy about the removal of a set of channels :thinking:

**Comment by xpromache** [comment]
> @xpromache is this what you hand in mind about removing the current User trait and implementation? 
I think it goes indeed in that direction.

> Still having the trouble that it needs the one off because of the multiplexed users in the testing.
Can you please point me to this problem of multiplexed users? I don't really understand it.


I made a drawing to get it all in my mind because I somehow feel it is too convoluted:
https://drive.google.com/file/d/1oz0oo4hBmZe7m80OlYjB0EayG-HIPbIG/view?usp=sharing

After I made the drawing I think I understand why I'm confused: it's because the daemon does things which I believe should be user responsibility - namely all the proxy operations.

For example what if a user does not want to execute a Proxy Put Request? Currently it's the daemon which is executing it automatically.

I'm not sure how to organize the code in a way to allow library users (i.e. other people using the cfdp library) to plug in bits and pieces of  (what I believe to be) user implementation currently residing in the Daemon ( for example the current Daemon::categorize_user_msg) and in the SendTransaction (the code in the "if self.config.send_proxy_response {").

Maybe just group the functions into a module  and in the example we provide, we show how a user can use those functions to process the messages, sending some of them back to the daemon.

**Comment by mkolopanis** [comment]
When I was reading through the specification documents they didn't seem like very optional things that could be done. Which is why I initially built them straight into the daemon. But I think if I understand what you're saying, even a implementation wants them to be automatic, the User instance really should be handling them and sending new Primitives to the Daemon?

I think your idea is as good a place to start as any. We may even find a better solution along the way. That would allow for the removal of the extra channel from the SendTransaction to the daemon (it's only used for sending a Proxy Put Response), but I think some more book keeping would need to be done so the user can get the OriginatingTransactionID from a transaction to send a Proxy Response.

I think some of the difficultly I'm having with imagining an implementation is how to set up tests too. Maybe it just needs a completely different test structure where every inter agency test has a separate user and daemon processes. But that seems like a lot of overhead.

**Comment by mkolopanis** [comment]
> For the ProxyPutRequest (A requests B to send a file to C) - it is the B user which should be receiving and decoding the MessageToUser containing the proxy put rquest, then it can initiate the requested Put transaction from B to C, monitor that transaction and at the end it can initiate the second transaction from B to A to notify the original requestor of the outcome. All that logic can be moved away from the Daemon/SentTransaction. It also gives the opportunity to the user B to verify the request and deny it if necessary.

Right the idea in my head was how to track with originating message is associated with each request. But like you're saying, that should just be each User implementation's own issue it can solve however it likes.

**Comment by xpromache** [comment]
> I think some of the difficultly I'm having with imagining an implementation is how to set up tests too. Maybe it just needs a completely different test structure where every inter agency test has a separate user and daemon processes. But that seems like a lot of overhead.

So I've been looking at the tests and I don't see where you have one daemon with multiple users.
What I see is local_user/local_daemon and remote_user/remote_daemon.

Am I missing something?

**Comment by mkolopanis** [comment]
I suppose multiple users isn't quite accurate, but there are multiple references to the local and remote user. Any test that uses the `get_filestore` fixture is returned a reference to both the local and remote user. 

I've noticed that when trying to move to a single channel to return information to the User from the Daemon, some responses are not necessarily returned in the expected order. So when one test is calling `local_user.put` and expecting to be returned the ID of the transaction, the next response from the daemon might be a report another test has created.

Maybe the test user interface just needs to be refined. it just seemed useful that when calling `put` or `report`, the caller should be returned the ID or report for the input transaction.

**Comment by xpromache** [comment]
Wow, I didn't realize that all those tests run in parallel sharing the same objects. I didn't even think that is possible in Rust. I only now see you can send a message to a channel without having mutable access to it...

In that case, what we can do is to keep the current scheme with a channel <(UserPrimitive, Sender<UserReturn>)> for request/replay patterns but add an additional channel for the asynchronous messages (what they call "indications" in the standard).

The test user can collect all those  messages into a HashMap<TransactionID, Vec<Message>> behind a Arc<Mutex<>> and the tests can lookup and verify the messages related to the transactions they initiated.

**Comment by mkolopanis** [comment]
oh good idea, then the test user just needs to spawn thread to listen on indications channel and update the hashmap as indications are received.

**Comment by mkolopanis** [comment]
I think I have most of the indications now but I think the Report indications could be all handled by the User too. I tried moving the report history and all the logic there up to the testuser but ran into some problems and wanted to roll back to a working commit for now.

**Comment by mkolopanis** [comment]
hmm i don't have these same issues on my personal windows machine. but I think if you want to look when you have time @xpromache I would appreciate it.

**Comment by xpromache** [comment]
> hmm i don't have these same issues on my personal windows machine. but I think if you want to look when you have time @xpromache I would appreciate it.

Looks that the windows built is quite slow probably due to limited CPU and what kills it is the tight sleep(1ms) in the f2 suite. I managed to pass the tests by replacing that with sleep(100ms) and allowing f8 and f9 to run for 15 seconds.

I believe there are some tight sleep loops still in the transport, I do plan to get rid of those after you have committed the user refactoring.

**Comment by mkolopanis** [comment]
Thanks! If you are interested in taking a closer look at this code I think it is ready too.

**Comment by xpromache** [comment]
> 

For me this can be merged. I did not have time to test it with my application but I will do it later.

**Comment by mkolopanis** [comment]
Thanks for getting back! I'm sure there's some tweaks we'll need!

**Pull request merged**
